title: atilileri
description: My random website
theme: just-the-docs

url: https://atilileri.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
